name: Publish Dev Image

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Variable Gathering
        id: gathervars
        run: |
          # get a current BUILD_DATE
          echo "BUILD_DATE=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          # set version based on BUILD_DATE
          echo "VERSION=$(date +%Y.%m.%d)-development" >> $GITHUB_OUTPUT

          # setting tags
          echo "TAG=development" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            BUILD_DATE=${{ steps.gathervars.outputs.BUILD_DATE }}
            VERSION=${{ steps.gathervars.outputs.VERSION }}
          context: ./docker/development
          tags: |
            ghcr.io/${{ github.repository }}-dev:latest
            ghcr.io/${{ github.repository }}-dev:${{ steps.gathervars.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64,linux/arm32v7
          push: true
